use alloy_rpc_client::ClientBuilder;
use alloy_rpc_types::{TransactionReceipt, Block};
use clap::Parser;
use dotenv::dotenv;
use std::env;
use url::Url;
use tracing::{info, warn, error};
use tracing_subscriber;
use serde_json;

#[derive(Parser)]
struct Args {
    /// User passes in a transaction hash.
    /// This transaction hash is trusted because it's generated by the user's wallet using the user's own private key.
    #[clap(short, long)]
    transaction_hash: Option<String>,
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();
    dotenv().ok();

    let rpc_url =
        Url::parse(&env::var("UNICHAIN_RPC").expect("need to set Unichain RPC in dotenv"))
            .expect("invalid RPC URL");
    info!("Parsed RPC URL. Using: {}", rpc_url);
    let client = ClientBuilder::default().http(rpc_url);

    let args = Args::parse();
    
    let transaction_hash: String = args.transaction_hash.unwrap_or_else(||{
        warn!("No transaction hash provided. Using default value instead.");
        info!("Default transaction hash: 0x1ae319ba1a236dffe07bcaa323948c9268225f4050ab7eaf86ab5930a937f162");
        "0x1ae319ba1a236dffe07bcaa323948c9268225f4050ab7eaf86ab5930a937f162".to_string()
    });
    
    let request = client.request("eth_getTransactionReceipt", (transaction_hash,));    
    let receipt: TransactionReceipt = request.await.expect("Failed to get transaction receipt during RPC call with error.");
    info!("Transaction receipt object: {:?}", receipt);

    let untrusted_block_number: u64 = receipt.block_number.expect("Failed to get block number from transaction receipt.");

    let request = client.request("eth_getBlockByNumber", (format!("0x{:x}", untrusted_block_number), true));
    let raw_response: serde_json::Value = request.await.expect("Failed to get block by number during RPC call with error.");
    // apparently alloy needs us to pass `true` to get all transactions and calculate the transaction root
    // let request = client.request("eth_getBlockByNumber", (format!("0x{:x}", untrusted_block_number), true));
    // let untrusted_block: Block = request.await.expect("Failed to get block by number during RPC call with error.");
    // info!("Block object: {:?}", untrusted_block);

    // info!("Transaction root: {:?}", untrusted_block.header.inner.transactions_root);

    // TODO: calcualte the transaction root, I guess I can't get the root from the RPC call..
    // let untrusted_transaction_root: String = untrusted_block

    // let request = client.request("eth_getBlockByNumber", (untrusted_block_number, true));
    // let untrusted_block = request.await.unwrap();

}
